"""
数据模型
"""

from typing import List, Optional
from dataclasses import dataclass
from enum import Enum


class Severity(Enum):
    """漏洞严重性等级"""
    CRITICAL = "Critical"
    HIGH = "High"
    MEDIUM = "Medium"
    LOW = "Low"
    INFO = "Info"


@dataclass
class Vulnerability:
    """漏洞信息"""
    name: str
    severity: Severity
    description: str
    remediation: str
    references: List[str] = None
    
    def __post_init__(self):
        if self.references is None:
            self.references = []


@dataclass
class ScanResult:
    """扫描结果"""
    url: str
    score: int
    vulnerabilities: List[Vulnerability]
    checked_items: int
    passed_items: int
    
    def save_report(self, path: str, format: str = "html"):
        """保存报告"""
        if format == "html":
            self._save_html_report(path)
        elif format == "json":
            self._save_json_report(path)
        else:
            raise ValueError(f"Unsupported format: {format}")
    
    def _save_html_report(self, path: str):
        """保存HTML报告"""
        html = f"""<!DOCTYPE html>
<html>
<head>
    <title>MCP Security Report</title>
    <style>
        body {{ font-family: Arial, sans-serif; margin: 40px; }}
        .score {{ font-size: 48px; font-weight: bold; }}
        .score-good {{ color: #28a745; }}
        .score-warning {{ color: #ffc107; }}
        .score-danger {{ color: #dc3545; }}
        .vulnerability {{ margin: 20px 0; padding: 15px; border-left: 4px solid; }}
        .critical {{ border-color: #dc3545; background: #f8d7da; }}
        .high {{ border-color: #fd7e14; background: #fff3cd; }}
        .medium {{ border-color: #ffc107; background: #fff3cd; }}
        .low {{ border-color: #17a2b8; background: #d1ecf1; }}
    </style>
</head>
<body>
    <h1>MCP Security Report</h1>
    <p><strong>URL:</strong> {self.url}</p>
    <p><strong>Checked Items:</strong> {self.checked_items}</p>
    <p><strong>Passed Items:</strong> {self.passed_items}</p>
    
    <div class="score {self._get_score_class()}">{self.score}/100</div>
    
    <h2>Vulnerabilities ({len(self.vulnerabilities)})</h2>
    {self._generate_vulnerabilities_html()}
    
    <hr>
    <p><em>Generated by MCP Security Scanner</em></p>
</body>
</html>"""
        
        with open(path, 'w') as f:
            f.write(html)
    
    def _save_json_report(self, path: str):
        """保存JSON报告"""
        import json
        
        data = {
            "url": self.url,
            "score": self.score,
            "checked_items": self.checked_items,
            "passed_items": self.passed_items,
            "vulnerabilities": [
                {
                    "name": v.name,
                    "severity": v.severity.value,
                    "description": v.description,
                    "remediation": v.remediation,
                    "references": v.references
                }
                for v in self.vulnerabilities
            ]
        }
        
        with open(path, 'w') as f:
            json.dump(data, f, indent=2)
    
    def _get_score_class(self) -> str:
        """获取评分CSS类"""
        if self.score >= 90:
            return "score-good"
        elif self.score >= 70:
            return "score-warning"
        else:
            return "score-danger"
    
    def _generate_vulnerabilities_html(self) -> str:
        """生成漏洞HTML"""
        if not self.vulnerabilities:
            return "<p>No vulnerabilities found ✅</p>"
        
        html = ""
        for vuln in self.vulnerabilities:
            severity_class = vuln.severity.value.lower()
            html += f"""
            <div class="vulnerability {severity_class}">
                <h3>[{vuln.severity.value}] {vuln.name}</h3>
                <p><strong>Description:</strong> {vuln.description}</p>
                <p><strong>Remediation:</strong> {vuln.remediation}</p>
                {self._generate_references_html(vuln.references)}
            </div>"""
        
        return html
    
    def _generate_references_html(self, references: List[str]) -> str:
        """生成参考链接HTML"""
        if not references:
            return ""
        
        links = [f'<a href="{ref}">{ref}</a>' for ref in references]
        return f'<p><strong>References:</strong> {", ".join(links)}</p>'
